version: "3.9"

services:
 # ------------------------------
  # Core Infrastructure Services
  # ------------------------------
  redis:
    image: redis:7.2
    container_name: redis
    ports:
      - "6379:6379"

  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"     # RabbitMQ messaging
      - "15672:15672"   # RabbitMQ management dashboard

  consul:
    image: hashicorp/consul:1.18
    container_name: consul
    ports:
      - "8500:8500"   # Consul web UI
    command: "agent -server -bootstrap -ui -client=0.0.0.0"

  traefik:
    image: traefik:v3.0
    container_name: traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"       # HTTP
      - "8080:8080"   # Traefik dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  # ------------------------------
  # Microservices
  # ------------------------------
  user-service:
  build: ./services/user-service
  container_name: user-service
  environment: 
    - MONGO_URI=mongodb://mongo:27017/userdb
    - CONSUL_HOST=consul
    - PORT= 4001
  depends_on:
    - mongo
    - consul
  labels:
    - "traefik.enable=true"
    - "traefik.http.routers.user.rule=PathPrefix(`/api/v1/users)"
    - "traefik.http.services.user.loadbalancer.server.port=4001"
  ports:
    - "4001:4001"

  product-service:
    build: ./services/product-service
    container_name: product-service
    environment:
      - MONGO_URI=mongodb://mongo:27017/productdb
      - CONSUL_HOST=consul
      - PORT=4000
    depends_on:
      - mongo
      - consul
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.product.rule=PathPrefix(`/api/v1/products`)"
      - "traefik.http.services.product.loadbalancer.server.port=4000"
    ports:
      - "4000:4000"  


volumes:
  mongo_data:
