version: '3.8'
services:
  consul:
    image: consul:1.18
    command: "agent -dev -client=0.0.0.0"
    ports:
      - "8500:8500"

  mongo:
    image: mongo:6
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"

  traefik:
    image: traefik:v2.10
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  user-service:
    build:
      context: ../services/user-service
      dockerfile: Dockerfile
    environment:
      - MONGO_URI=mongodb://mongo:27017/userdb
      - JWT_SECRET=supersecret
      - PORT=3000
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - consul
      - rabbitmq
    labels:
      - "traefik.http.routers.user.rule=PathPrefix(`/api/v1/auth`)"
      - "traefik.http.services.user.loadbalancer.server.port=3000"
  
volumes:
  mongo-data:
